[project]
name = "pixi"
version = "0.1.0"
description = "Add a short description here"
authors = ["Your Name <you@example.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.11"
